config/routes.rb
Rails.application.routes.draw do
  get 'house/index'
  get 'house/edit'
  devise_for :users, controllers: { registrations: "users/registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "stories#index"

  resources :users, only: [:show, :index, :edit]
  resources :stories, only: [:create, :new, :index, :show, :edit, :update] do
    resources :comments, only: [:create]
  end
  resources :artists, only: [:show]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :stories
  has_many :likes
  has_many :stories, through: :likes
  has_many :notifications
  has_many :stories, through: :notifications
  has_one_attached :avatar
  has_many :comments

  before_create :skip_user_confirmation

  def skip_user_confirmation
    skip_confirmation!
  end

  def fullname
    "#{first_name} #{last_name}"
  end

  def unviewed_notifications_count
    notifications.where(viewed: false).count
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    # More info at:
    # https://github.com/heartcombo/devise#omniauth

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end

    def update_resource(resource, params)
      resource.update_without_password(params.except("current_password"))
    end

    def after_update_path_for(resource)
      user_path(resource)
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :index, :edit]

  def show
    @stories = @user.stories
  end

  def edit; end

  private

  def find_user
    @user = User.includes(:stories).find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.haml
.user-info.text-center.mb-4
	.user-avatar
		= model_avatar(@user, 'rounded-circle avatar mt-3')
	.user-name
		= @user.email

.row
	.col-md-8
		.stories-options
			%fieldset.border.border-dark.border-dashed.rounded-3.p-3
				%legend.float-none.w-auto.px-3 Stories

				.stories-actions
					.new-story.p-3.border.rounded-5.bg-light.d-flex
						= image_tag 'icons/pencil-fill.svg', class: 'new-icon'
						= link_to 'Nouvelle histoire', new_story_path, class: 'new-story-section flex-grow-1', data: { turbo: false }
						= image_tag 'icons/plus-lg.svg', class: 'new-plus-icon'
					.all-story.p-3.border.rounded-5.bg-light.mt-2
						#accordionExample.accordion
							.accordion-item
								%h2#headingOne.accordion-header
									%button.accordion-button.collapsed{"aria-controls" => "collapseOne", "aria-expanded" => "true", "data-bs-target" => "#collapseOne", "data-bs-toggle" => "collapse", type: "button"}
										= image_tag 'icons/book-fill.svg', class: 'stories-icons'
										Vos histoires
								#collapseOne.accordion-collapse.collapse{"aria-labelledby" => "headingOne", "data-bs-parent" => "#accordionExample"}
									.accordion-body
										- @stories.each do |story|
											.story-link
												= link_to story_path(story) do
													= story.title
											%hr

		.account-user
			%fieldset.border.border-dark.border-dashed.rounded-3.p-3
				%legend.float-none.w-auto.px-3 Compte

				.account-info
					.d-flex.justyfy-content-center.user-info
						.avatar-user
							= model_avatar(@user, 'avatar rounded-circle')
							.edit.text-center
								= link_to edit_user_registration_path, class: 'edit-icons' do
									= image_tag 'icons/pencil-square.svg'
						%h3.user_fullname
							= @user.fullname
						
							.login-email
								login: 
								= @user.email
							.login-password
								mot de passe:...............


	.col-md-4
		.contributors
			%fieldset.border.border-dark.border-dashed.rounded-3.p-3
				%legend.float-none.w-auto.px-3 Contributeurs
				.row.contributors
					- @stories.each do |story|
						- story.contributions.each do |contributor|
							.col-md-4.user-avatar
								= model_avatar(contributor.user, 'avatar rounded-circle')