config/routes.rb
Rails.application.routes.draw do
  get 'house/index'
  get 'house/edit'
  devise_for :users, controllers: { registrations: "users/registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "stories#index"

  resources :users, only: [:show, :index, :edit]
  resources :stories, only: [:create, :new, :index, :show, :edit, :update] do
    resources :comments, only: [:create]
  end
  resources :artists, only: [:show]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :stories
  has_one_attached :avatar

  before_create do
    self.name = name.downcase
  end

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :story

  validates :body, presence: true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :story
  belongs_to :user

  def self.contribute(contributor, story)
    return if contributor.id == story.user.id

    find_or_create_by(user_id: contributor.id, story_id: story.id)
  end
end

app/models/era.rb
class Era < ApplicationRecord
	has_many :stories
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :story_genres
	has_many :stories, through: :story_genres

	validates :name, presence: true

	before_create do
		self.name = name.downcase
	end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :story
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :story, optional: true
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  belongs_to :era
  belongs_to :artist
  has_many :story_genres
  has_many :genres, through: :story_genres
  has_many :contributions
  has_many :users, through: :contributions
  has_many :likes
  has_many :users, through: :likes
  has_many :notifications
  has_many :users, through: :notifications
  has_many :comments

  accepts_nested_attributes_for :artist

  has_rich_text :body
  has_one_attached :avatar

  validates :title, :body, presence: true

  before_create do
    self.title = title.downcase
  end
  before_create :existing_artist

  def existing_artist
    artist = Artist.find_by(name: self.artist.name)

    self.artist = artist
  end

  def contributors_count
    contributions.count
  end
end

app/models/story_genre.rb
class StoryGenre < ApplicationRecord
  belongs_to :story
  belongs_to :genre
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :stories
  has_many :likes
  has_many :stories, through: :likes
  has_many :notifications
  has_many :stories, through: :notifications
  has_one_attached :avatar
  has_many :comments

  before_create :skip_user_confirmation

  def skip_user_confirmation
    skip_confirmation!
  end

  def fullname
    "#{first_name} #{last_name}"
  end

  def unviewed_notifications_count
    notifications.where(viewed: false).count
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :artist, only: [:show]

  def show
    @stories = @artist.stories
  end

  private

  def artist
    @artist = Artist.find(params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :story

  def create
    Like.create(user_id: current_user.id, story_id: @story.id)
    redirect_to story_path(@story)
  end

  def destroy
    @like = Like.find(params[:id])

    @like.destroy
    redirect_to story_path(@story)
  end

  private

  def story
    @story = Story.find(params[:like][:story_id])
  end

  def like_params
    params.require(:like).permit(:user_id, :story_id)
  end
end

app/controllers/stories_controller.rb
# frozen_string_literal: true

class StoriesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  before_action :find_story, only: %i[show edit update destroy]
  before_action :find_like, only: %i[show edit update destroy]

  def index
    @stories = SearchStories.call(Story.all, params[:q])
  end

  def new
    @story = Story.new
    @artist = @story.build_artist
  end

  def create
    @story = current_user.stories.new(story_params)
    @story.user_id = current_user.id

    if @story.save
      redirect_to story_path(@story), notice: t('activerecord.controllers.stories.create.success')
    else
      render 'new'
    end
  end

  def show
    @comment = Comment.new
    @comments = @story.comments
  end

  def edit; end

  def update
    if @story.update(story_params)
      SendNotificationsService.new(Contribution.contribute(current_user, @story), current_user, @story).call
      redirect_to story_path(@story), notice: t('activerecord.controllers.stories.update.success')
    else
      render 'edit'
    end
  end

  private

  def find_story
    @story = Story.find(params[:id])
  end

  def find_like
    @like = @story.likes.find_by(user_id: current_user.id, story_id: @story.id) if current_user
  end

  def story_params
    params.require(:story).permit(:title, :artist_name, :body, :user_id, :era_id, :avatar,
                                  artist_attributes: [:id, :name, :avatar], genre_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :index, :edit]

  def show
    @stories = @user.stories
  end

  def edit; end

  private

  def find_user
    @user = User.includes(:stories).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def model_avatar(model, css)
    if model.avatar.url
      image_tag(model.avatar.url, class: css)
    else
      image_tag('empty-avatar.png', class: css)
    end
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notification_helper.rb
module NotificationHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
  def story_title(title)
    %("#{title}")
  end

  def story_form_title(story)
    if story.new_record?
      'Nouvelle histoire'
    else
      'Editer votre histoire'
    end
  end

  def edit_button_label(story)
    return 'Contribuer' unless story.user.id == current_user.id

    'Editer votre histoire'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artists/show.haml
.artist-info.text-center
	.d-flex.align-items-center.justify-content-center
		.avatar-story
			= model_avatar(@artist, 'rounded-circle avatar mt-3')
		%h3.artist-name
			= @artist.name.capitalize

.stories-artist.mt-5
	= render StoriesComponent.new(stories: @stories)

app/views/stories/edit.haml
.new-story.mx-auto.mt-4.border.border-light.w-75.p-4
	= render(StoryFormComponent.new(story: @story))

app/views/stories/index.haml
.title.text-center.mt-5
	Tunes_stories
	%h5.bold Discover how it happened


.search-section.mt-5
	= simple_form_for :q, url: "/stories", method: :get, id: 'search-story', data: { turbo_frame: 'stories'} do |f|
		= f.input :queries, label: false, required: false, input_html: { class: 'form-control m-auto p-3 rounded-5', id: 'form1', placeholder: 'Search for song/album/artist' }

		.row
			.col-md-2
			.col-md-2
			.col-md-2.genres-filter.form-group
				= f.input :genres, label: false, collection: Genre.all.map { |g| g.name.capitalize }, input_html: { id: 'genres-filters', class: 'rounded-5'}

			.col-md-2.era-filter.form-group
				= f.input :era, label: false, collection: Era.all.map { |e| e.year }.reverse, input_html: {class: 'form-control rounded-5', prompt: 'Année' }
			.col-md-2
				= f.submit 'Search', class: 'search-button btn btn-primary rounded-5'
			.col-md-2

= turbo_frame_tag 'stories' do
	= render StoriesComponent.new(stories: @stories)

app/views/stories/new.haml
.new-story.mx-auto.mt-4.border.border-light.w-75.p-4
	= render(StoryFormComponent.new(story: @story))

app/views/stories/show.haml
.row
	.col-md-8.border-right-0
		.artist-info.text-center
			.d-flex.align-items-center.justify-content-center
				.avatar-story
					= model_avatar(@story.artist, 'rounded-circle avatar mt-3')
				%h3.artist-name
					= link_to @story.artist.name.capitalize, artist_path(@story.artist), class: 'link-story'

		.paper-story-background
			.paper-story.bg-white.pt-5.mt-3
				%h1.title.text-center
					= story_title(@story.title.capitalize)

				.story-descrition.mt-4
					= @story.body.body

		- if user_signed_in?
			.comment-form.mt-5.mb-5
				= render CommentFormComponent.new(comment: @comment, story: @story)

		.comments
			= render CommentsListComponent.new(comments: @comments)

	.col-md-4.border-left.border-dark.pt-5
		- if user_signed_in?
			.edit-story.d-grid.gap-2
				= link_to edit_button_label(@story), edit_story_path(@story), class: 'btn btn-primary d', data: { turbo: false }
		- if user_signed_in?
			%hr
			- if @like.nil?
				.like.ml-auto
					= button_to likes_path(like: { story_id: @story.id, user_id: current_user.id }), method: "post", data: { turbo: 'false' } do
						= image_tag('icons/hand-thumbs-up.svg')
			- else
				.dislike
					= button_to like_path(@like, like: { story_id: @story.id }), method: "delete", data: {turbo: 'false' } do
						= image_tag('icons/hand-thumbs-up.svg')					
			
			.likes-count
				= @story.likes.count
				- if @story.likes.count > 1
					personnes aiment
				- else
					personne aime

		%hr
		.contributors
			%h5 Contributions

			Nombre de contributeurs: 
			= @story.contributors_count
			.contributors-avatars
				- @story.contributions.each do |contributor|
					.user-avatars
						= link_to user_path(contributor.user) do
							= image_tag contributor.user.avatar.url, class: 'avatar rounded-5'
		%hr
		.story-info
			.story-info.title
				%h5 Informations générale
			.year-info
				Année:
				= @story.era.year

			.artist-name
				Artiste:
				= @story.artist.name.capitalize